### ISSUE TITLE
Autoupdater is failing

### ISSUE THREAD

**Issue by Chafficui** [Chafficui/CrucialAPI#5]
```[17:31:32] [Thread-18/INFO]: [CrucialAPI] Checking for update...
[17:31:32] [Thread-18/INFO]: [CrucialAPI] Update found, downloading now...
[17:31:32] [Thread-18/WARN]: io.github.chafficui.CrucialAPI.exceptions.CrucialException: Error 008: Updater tried to download the update, but was unsuccessful.
[17:31:32] [Thread-18/WARN]: 	at CrucialAPI-v2.0.1.jar//io.github.chafficui.CrucialAPI.Utils.api.Updater.download(Updater.java:214)
[17:31:32] [Thread-18/WARN]: 	at CrucialAPI-v2.0.1.jar//io.github.chafficui.CrucialAPI.Utils.api.Updater.checkUpdate(Updater.java:160)
[17:31:32] [Thread-18/WARN]: 	at CrucialAPI-v2.0.1.jar//io.github.chafficui.CrucialAPI.Utils.api.Updater.access$200(Updater.java:15)
[17:31:32] [Thread-18/WARN]: 	at CrucialAPI-v2.0.1.jar//io.github.chafficui.CrucialAPI.Utils.api.Updater$UpdaterRunnable.run(Updater.java:241)
[17:31:32] [Thread-18/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)```

**Comment by Chafficui** [comment]
Fixed in the next update
